import Head from 'next/head';
import RealZeroPage from './main';

export default function Home() {
  return (
    <>
      <Head>
        <title>리얼제로</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/img/realzero_favicon.png" />
      </Head>
      <RealZeroPage />
    </>
  );
}
